name: Execute Test Script

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
        type: choice
        options:
          - info
          - warning
          - debug
      tags:
        description: "Test scenario tags"
        required: false
        type: boolean
      environment:
        description: "Environment to run tests against"
        type: environment
        required: true
  repository_dispatch:
    types: [run-test-script]

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install TypeScript
        run: yarn add typescript --dev

      - name: Install ts-node
        run: yarn global add ts-node

      - name: Run Test Script
        run: $(yarn global bin)/ts-node src/app/test.ts
